---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations: {}
  name: "nginx-master"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: "nginx-master"
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "nginx-master"
      annotations: {}
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      containers:
      - name: "nginx-master"
        image: "nginx:latest"
        imagePullPolicy: "IfNotPresent"
---
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  selector:
    app: foo 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: foo-https
spec:
  selector:
    app: foo
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
