---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations: {}
  name: "nginx-master"
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "nginx-master"
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "nginx-master"
        app: "nginx-master"
      annotations: {}
    spec:
      terminationGracePeriodSeconds: 15
      nodeSelector: {}
      containers:
      - name: "nginx-master"
        image: "nginx:latest"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: BAR3
          value: "I can not do that Dave?"
        - name: FOOburger
          value: "Eaten"
---
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  selector:
    app: foo 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: foo-https
spec:
  selector:
    app: foo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
